// path: src/constant/dummyPosts.ts

export interface PostType {
  id: string;
  author: string;
  circle: string;
  time: string;
  content: string;
  supportCount: number;
  helpfulCount: number;
  commentCount: number;
  image?: string;
  videoUrl?: string; // Used to tell the PostCard to render a video player or thumbnail
}

export const dummyPosts: PostType[] = [
  {
    id: "1",
    author: "Sarah",
    circle: "Fibromyalgia Warriors",
    time: "23m ago",
    content: "Finally found a sleep routine that actually works. After 3 years of terrible sleep, I tried the 4-7-8 breathing method combined with a heating pad and it has helped tremendously.",
    supportCount: 24,
    helpfulCount: 11,
    commentCount: 8,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
  },
  {
    id: "2",
    author: "John",
    circle: "Diabetes Circle",
    time: "1h ago",
    content: "Has anyone experienced dizziness after switching medications? Curious about others' experiences.",
    supportCount: 12,
    helpfulCount: 5,
    commentCount: 16,
  },
  {
    id: "3",
    author: "Elena",
    circle: "Mental Wellness",
    time: "2h ago",
    content: "Just finished a 10-minute guided meditation. I recorded a quick video sharing the exact techniques that helped calm my anxiety today. Give it a try!",
    supportCount: 45,
    helpfulCount: 30,
    commentCount: 12,
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4", 
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b", // Thumbnail for video
  },
  {
    id: "4",
    author: "Marcus",
    circle: "Heart Health",
    time: "3h ago",
    content: "Meal prep Sunday! Low sodium doesn't have to mean low flavor. Check out this Mediterranean bowl I threw together. Recipe in the comments! 🥗",
    supportCount: 89,
    helpfulCount: 62,
    commentCount: 21,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    id: "5",
    author: "David",
    circle: "Chronic Pain Support",
    time: "4h ago",
    content: "Upgraded my home office with an ergonomic chair. For anyone dealing with lower back issues, investing in your workspace makes a world of difference.",
    supportCount: 34,
    helpfulCount: 18,
    commentCount: 5,
  },
  {
    id: "6",
    author: "Aisha",
    circle: "PCOS Warriors",
    time: "5h ago",
    content: "Strength training has completely changed my energy levels. Here is a quick snippet of my morning routine. Remember, start slow!",
    supportCount: 112,
    helpfulCount: 88,
    commentCount: 34,
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a",
  },
  {
    id: "7",
    author: "Chloe",
    circle: "Anxiety Relief",
    time: "6h ago",
    content: "Reminder: The '5-4-3-2-1' grounding technique works wonders. 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste.",
    supportCount: 250,
    helpfulCount: 198,
    commentCount: 42,
  },
  {
    id: "8",
    author: "Sam",
    circle: "Gut Health",
    time: "7h ago",
    content: "First attempt at making my own Kombucha! The fermentation process is fascinating. Has anyone else tried this?",
    supportCount: 41,
    helpfulCount: 12,
    commentCount: 19,
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721",
  },
  {
    id: "9",
    author: "Maya",
    circle: "Migraine Relief",
    time: "8h ago",
    content: "The barometric pressure dropped significantly today and I can feel a migraine coming on. Taking my meds early and staying in a dark room. Stay safe everyone.",
    supportCount: 76,
    helpfulCount: 10,
    commentCount: 28,
  },
  {
    id: "10",
    author: "Liam",
    circle: "Fitness Journey",
    time: "10h ago",
    content: "Ran my first 5k today! Six months ago I couldn't run for 60 seconds without losing my breath. Consistency is everything. 🏃‍♂️💨",
    supportCount: 405,
    helpfulCount: 50,
    commentCount: 65,
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211",
  },
  {
    id: "11",
    author: "Emma",
    circle: "Sleep Apnea",
    time: "11h ago",
    content: "Struggling to adjust to my new CPAP machine. The mask feels so intrusive. Any veteran users have tips for the first few weeks?",
    supportCount: 55,
    helpfulCount: 22,
    commentCount: 31,
  },
  {
    id: "12",
    author: "Noah",
    circle: "ADHD Brains",
    time: "12h ago",
    content: "I built a visual timer to help me focus during work. I recorded a quick demo of how I use it with the Pomodoro technique. Total game changer.",
    supportCount: 180,
    helpfulCount: 145,
    commentCount: 27,
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    image: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d",
  },
  {
    id: "13",
    author: "Olivia",
    circle: "Thyroid Health",
    time: "14h ago",
    content: "Does anyone else hit a massive energy wall around 3 PM? Trying to figure out if it's my medication timing or just diet.",
    supportCount: 88,
    helpfulCount: 15,
    commentCount: 44,
  },
  {
    id: "14",
    author: "Lucas",
    circle: "Arthritis Support",
    time: "16h ago",
    content: "Water aerobics has been so gentle on my joints. Highly recommend checking if your local rec center offers classes!",
    supportCount: 67,
    helpfulCount: 33,
    commentCount: 9,
    image: "https://images.unsplash.com/photo-1530549387789-4c1017266635",
  },
  {
    id: "15",
    author: "Mia",
    circle: "Skin Conditions",
    time: "18h ago",
    content: "Currently going through a severe eczema flare-up. Oatmeal baths and heavy ceramide creams are my best friends right now. Hang in there if you're dealing with the same.",
    supportCount: 120,
    helpfulCount: 45,
    commentCount: 22,
  },
  {
    id: "16",
    author: "Ethan",
    circle: "Asthma Care",
    time: "20h ago",
    content: "Friendly reminder from your local respiratory therapist to ALWAYS use a spacer with your inhaler! I made a quick video showing the difference it makes.",
    supportCount: 310,
    helpfulCount: 280,
    commentCount: 41,
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae",
  },
  {
    id: "17",
    author: "Ava",
    circle: "Depression Support",
    time: "22h ago",
    content: "Today I actually got out of bed, took a shower, and made a real meal. It feels small, but to me, it's a huge victory.",
    supportCount: 890,
    helpfulCount: 0,
    commentCount: 115,
  },
  {
    id: "18",
    author: "William",
    circle: "Nutrition Basics",
    time: "1d ago",
    content: "Look at the colors on this plate! Eating the rainbow isn't just a saying, it's the best way to ensure you're getting a variety of micronutrients. 🌈",
    supportCount: 145,
    helpfulCount: 76,
    commentCount: 18,
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061",
  },
  {
    id: "19",
    author: "Isabella",
    circle: "Endometriosis",
    time: "1d ago",
    content: "My heating pad is permanently attached to my body today. Sending love to anyone else fighting invisibly today.",
    supportCount: 215,
    helpfulCount: 40,
    commentCount: 52,
    image: "https://images.unsplash.com/photo-1520333789090-1afc82db536a",
  },
  {
    id: "20",
    author: "James",
    circle: "General Wellness",
    time: "1d ago",
    content: "Drink a glass of water right now. Yes, right now. You're welcome! 💧",
    supportCount: 540,
    helpfulCount: 320,
    commentCount: 14,
  }
];