const imagePath = {
    googleIcon : require("../assets/icons/google.png"),
    appleIcons: require("../assets/icons/apple.png"),
    UserIcon: require("../assets/icons/users.png"),
    ShieldIcon: require("../assets/icons/shield.png"),
    HeartIcon: require("../assets/icons/heart.png"),
    SearchIcon: require("../assets/icons/search.png"),
    NotificationIcon: require("../assets/icons/notification.png"),
    AlertIcon: require("../assets/icons/alert.png"),
    RightIcon: require("../assets/icons/right-arrow.png"),
    LeftIcon: require("../assets/icons/left-arrow.png"),
    PostIcon: require("../assets/icons/post.png"),
    LoveIcon: require("../assets/icons/love.png"),
    ShareIcon: require("../assets/icons/send.png"),
    HomeIcon: require("../assets/icons/home.png"),
    GroupIcon: require("../assets/icons/people.png"),
    ChatIcon: require("../assets/icons/chat.png"),
    HelpIcon: require("../assets/icons/staff.png"),
    User: require("../assets/icons/user2.png"),
    Help: require("../assets/icons/help.png"),
    ReportIcon: require("../assets/icons/report.png"),
    UploadIcon: require("../assets/icons/upload.png"),
    StarIcon: require("../assets/icons/star.png"),
    VideoIcon: require("../assets/icons/Video.png"),
    ClockIcon: require("../assets/icons/clock.png"),
    PhoneIcon: require("../assets/icons/phone.png"),
    LanguageIcon: require("../assets/icons/language.png"),
    MoneyIcon: require("../assets/icons/money.png"),
    InfinityMark: require("../assets/icons/infinity-mark.png"),
    MoreIcon: require("../assets/icons/more.png"),
    SettingIcon: require("../assets/icons/setting.png"),
} as const;

export default imagePath